applications:
    - name: simple-app
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: default
      source:
        repoURL: https://github.com/SmbatSakanyan/Kubernetes-project
        targetRevision: main
        path: Helm
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

