image:
  tag: "v0.12.2"

config:
    registries:
      - name: ECR
        api_url: "https://548844171305.dkr.ecr.us-east-2.amazonaws.com"
        prefix: 548844171305.dkr.ecr.us-east-2.amazonaws.com
        default: true
        ping: yes
        insecure: no
        credentials: ext:/scripts/ecr-login.sh  #script name should match here and in authScripts 
        credsexpire: 11h
authScripts:
    enabled: true
    scripts: 
        ecr-login.sh: |   # notice script name matches above    
          #!/bin/sh
          aws ecr --region us-east-2 get-authorization-token --output text --query 'authorizationData[0].authorizationToken' | base64 -d
# serviceAccount:
#     create: true
#     annotations:
#         eks.amazonaws.com/role-arn: arn:aws:iam::548844171305:role/develop-image-updater-role