applications:
    - name: simple-app
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: 548844171305.dkr.ecr.us-east-2.amazonaws.com/dimple-app:~v0.5.0main-0e313be
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      project: default
      source:
        repoURL: https://github.com/SmbatSakanyan/Kubernetes-project
        targetRevision: main
        path: Helm
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

