
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 14.12.2
    helm:
      values: |
        image:
          tag: 5.0.24-debian-11-r20
        persistence:
          size: 10Gi
        auth:
          rootPassword: "test1234"
          usernames: [ "velvioo" ]
          passwords: [ "testpass" ]
          databases: [ "velvioo" ]
          enabled: true
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
