apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 14.12.2
    helm:
      values: |
        image:
          tag: 5.0-debian-11
        persistence:
          size: 10Gi
        auth:
          usernames: [ "velvioouser" ]
          passwords: [ "testpass" ]
          databases: [ "velvioo" ]
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
