apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ride-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      values: |
        containers:
          tag: ride
        ports:
          container_port: 8088
    repoURL: https://github.com/Khachik001/helm
    targetRevision: main
    path: Chart-test
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
