apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-app
  namespace: argocd
  # annotations:
  #     argocd-image-updater.argoproj.io/image-list: simple-app=548844171305.dkr.ecr.us-east-2.amazonaws.com/dimple-app
  #     argocd-image-updater.argoproj.io/simple-app.update-strategy: latest
  #     argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      values: |
        containers.tag: user_redis
        ports.container_port: 8087
    repoURL: https://github.com/Khachik001/helm
    targetRevision: main
    path: Chart-test
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
